Library/football/config/routes.rb
Football::Application.routes.draw do
  get "main/index"

  resources :nfl_games

  resources :players

  resources :drafts

  resources :games

  resources :teams

  resources :owners

  resources :users

  get "admin/index"

  resources :divisions

  resources :leagues

   root :to => 'admin#index'

end

Library/football/app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :league
  has_many :owners
  validates :league_id, :name, :year, presence: true
  validates :year, numericality: {greater_than_or_equal_to: 2000}

end

Library/football/app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :player
  belongs_to :owner
end

Library/football/app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Owner", :foreign_key => "home_team_id"
  belongs_to :away_team, :class_name => "Owner", :foreign_key => "away_team_id"
end

Library/football/app/models/league.rb
class League < ActiveRecord::Base
  has_many :divisions
  has_many :drafts
  validates :name, presence: true
  validates :name, uniqueness: true

end

Library/football/app/models/nfl_game.rb
class NflGame < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Team", :foreign_key => "home_team_id"
  belongs_to :away_team, :class_name => "Team", :foreign_key => "away_team_id"
  belongs_to :winner, :class_name => "Team", :foreign_key => "winner_id"
end

Library/football/app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  belongs_to :division
  has_many :games
  has_many :drafts
  validates :user_id, :division_id, presence: true

  def team_name
    "#{name_1} #{name_2}"
  end

end

Library/football/app/models/player.rb
class Player < ActiveRecord::Base
  has_many :drafts
  belongs_to :current_team, :class_name => "Team", :foreign_key => "current_team_id" 

  def full_name
    "#{first_name} #{last_name}"
  end

end

Library/football/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  has_many :nfl_games


  def full_name
    "#{location} #{name}"
  end

end

Library/football/app/models/user.rb
class User < ActiveRecord::Base
  has_many :owners
  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

Library/football/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @owners = Owner.all
  end

end

Library/football/app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.json
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(params[:owner])

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render action: "new" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.json
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :ok }
    end
  end
end

Library/football/app/helpers/admin_helper.rb
module AdminHelper
end

Library/football/app/helpers/application_helper.rb
module ApplicationHelper
end

Library/football/app/helpers/divisions_helper.rb
module DivisionsHelper
end

Library/football/app/helpers/drafts_helper.rb
module DraftsHelper
end

Library/football/app/helpers/games_helper.rb
module GamesHelper
end

Library/football/app/helpers/leagues_helper.rb
module LeaguesHelper
end

Library/football/app/helpers/main_helper.rb
module MainHelper
end

Library/football/app/helpers/nfl_games_helper.rb
module NflGamesHelper
end

Library/football/app/helpers/owners_helper.rb
module OwnersHelper
end

Library/football/app/helpers/players_helper.rb
module PlayersHelper
end

Library/football/app/helpers/teams_helper.rb
module TeamsHelper
end

Library/football/app/helpers/users_helper.rb
module UsersHelper
end

Library/football/app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :division_id %><br />
    <%= f.number_field :division_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name_1 %><br />
    <%= f.text_field :name_1 %>
  </div>
  <div class="field">
    <%= f.label :name_2 %><br />
    <%= f.text_field :name_2 %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br />
    <%= f.text_field :logo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library/football/app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

Library/football/app/views/owners/index.html.erb
<h1>Owners</h1>

<table>
<% @owners.each do |owner| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td class="list_name">
      <dl>
        <dt><%= owner.division.league.name %></dt>
        <dt><%= owner.division.name %></dt>
        <dt><%= owner.user.full_name %></dt>
        <dt><%= owner.team_name %></dt>
        <dt><%= owner.symbol %></dt>
      </dl>
    </td>

    <td class="list_actions">

      <%= link_to 'Show', owner %>,<br />
      <%= link_to 'Edit', edit_owner_path(owner) %><br />
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Owner', new_owner_path %>

Library/football/app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

Library/football/app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Division:</b>
  <%= @owner.division_id %>
</p>

<p>
  <b>User:</b>
  <%= @owner.user_id %>
</p>

<p>
  <b>Name 1:</b>
  <%= @owner.name_1 %>
</p>

<p>
  <b>Name 2:</b>
  <%= @owner.name_2 %>
</p>

<p>
  <b>Symbol:</b>
  <%= @owner.symbol %>
</p>

<p>
  <b>Logo url:</b>
  <%= @owner.logo_url %>
</p>


<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>