Library/football/config/routes.rb
Football::Application.routes.draw do
  get "main/index"

  resources :nfl_games

  resources :players

  resources :drafts

  resources :games

  resources :teams

  resources :owners

  resources :users

  get "admin/index"

  resources :divisions

  resources :leagues

   root :to => 'admin#index'

end

Library/football/app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :league
  has_many :owners
  validates :league_id, :name, :year, presence: true
  validates :year, numericality: {greater_than_or_equal_to: 2000}

end

Library/football/app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :player
  belongs_to :owner
end

Library/football/app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Owner", :foreign_key => "home_team_id"
  belongs_to :away_team, :class_name => "Owner", :foreign_key => "away_team_id"
end

Library/football/app/models/league.rb
class League < ActiveRecord::Base
  has_many :divisions
  has_many :drafts
  validates :name, presence: true
  validates :name, uniqueness: true

end

Library/football/app/models/nfl_game.rb
class NflGame < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Team", :foreign_key => "home_team_id"
  belongs_to :away_team, :class_name => "Team", :foreign_key => "away_team_id"
  belongs_to :winner, :class_name => "Team", :foreign_key => "winner_id"
end

Library/football/app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  belongs_to :division
  has_many :games
  has_many :drafts
  validates :user_id, :division_id, presence: true

  def team_name
    "#{name_1} #{name_2}"
  end

end

Library/football/app/models/player.rb
class Player < ActiveRecord::Base
  has_many :drafts
  belongs_to :current_team, :class_name => "Team", :foreign_key => "current_team_id" 

  def full_name
    "#{first_name} #{last_name}"
  end

end

Library/football/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  has_many :nfl_games


  def full_name
    "#{location} #{name}"
  end

end

Library/football/app/models/user.rb
class User < ActiveRecord::Base
  has_many :owners
  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

Library/football/app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :ok }
    end
  end
end

Library/football/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @owners = Owner.all
  end

end

Library/football/app/helpers/admin_helper.rb
module AdminHelper
end

Library/football/app/helpers/application_helper.rb
module ApplicationHelper
end

Library/football/app/helpers/divisions_helper.rb
module DivisionsHelper
end

Library/football/app/helpers/drafts_helper.rb
module DraftsHelper
end

Library/football/app/helpers/games_helper.rb
module GamesHelper
end

Library/football/app/helpers/leagues_helper.rb
module LeaguesHelper
end

Library/football/app/helpers/main_helper.rb
module MainHelper
end

Library/football/app/helpers/nfl_games_helper.rb
module NflGamesHelper
end

Library/football/app/helpers/owners_helper.rb
module OwnersHelper
end

Library/football/app/helpers/players_helper.rb
module PlayersHelper
end

Library/football/app/helpers/teams_helper.rb
module TeamsHelper
end

Library/football/app/helpers/users_helper.rb
module UsersHelper
end

Library/football/app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br />
    <%= f.number_field :league_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library/football/app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

Library/football/app/views/divisions/index.html.erb
<h1>League Divisions</h1>

<table>
<% @divisions.each do |division| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td class="list_name">
      <dl>
        <dt><%= division.league.name %></dt>
        <dt><%= division.name %></dt>
        <dt><%= division.year %></dt>
      </dl>
    </td>

    <td class="list_actions">

      <%= link_to 'Show', division %>,<br />
      <%= link_to 'Edit', edit_division_path(division) %><br />
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Division', new_division_path %>

Library/football/app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

Library/football/app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>League:</b>
  <%= @division.league_id %>
</p>

<p>
  <b>Name:</b>
  <%= @division.name %>
</p>

<p>
  <b>Year:</b>
  <%= @division.year %>
</p>


<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>